on:
  release:
    types: [created]

jobs:
  test-code:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check-go-fmt
        run: test -z `go fmt ./...`
      - name: test
        run: go test ./...

  release-binaries:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: test-code
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm64, amd64]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          build_command: make build
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
